#!/bin/sh
aws ec2 describe-instances \
	--query 'Reservations[0].Instances[0].PrivateIpAddress' \
	--filters \
		Name=tag:Cluster,Values=workbench \
		Name=tag:Team,Values=$SEGMENT_TEAM \
	--output=text
